import { useEffect, useState } from 'react'
import { Link, createFileRoute } from '@tanstack/react-router'
import { AnimatePresence, motion } from 'framer-motion'
import { ChevronDown, Globe2, Menu, Search, ShoppingCart, X } from 'lucide-react'
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { toast } from 'sonner'

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'ALD Pulse — Your one-stop marketplace for ALD / ALE / MLD needs' },
    { name: 'description', content: 'Source qualified thermocouples, gaskets, fittings, precursors, bubblers, MFCs and more from one ALD marketplace.' },
  ] }),
  component: HomePage,
})

type Product = { id: string; name: string; part: string; vendor: string; category: string; spec: string; price: number; image: string; processes: string[]; featured?: boolean }

type Category = { name: string; slug: string; image: string; count: number }

const categories: Category[] = [
  { name: 'Valves & Flow Control', slug: 'valves-flow-control', image: 'https://images.unsplash.com/photo-1565514020179-026b92b2d70b?auto=format&fit=crop&w=900&q=85', count: 82 },
  { name: 'MFCs', slug: 'mfcs', image: 'https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&w=900&q=85', count: 31 },
  { name: 'Thermocouples', slug: 'thermal-sensing', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=85', count: 38 },
  { name: 'Gaskets & O-rings', slug: 'seals-elastomers', image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=85', count: 29 },
  { name: 'Fittings', slug: 'fittings', image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=85', count: 45 },
  { name: 'Precursor Containers & Bubblers', slug: 'precursor-containers', image: 'https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&w=900&q=85', count: 24 },
  { name: 'Precursor Chemicals', slug: 'precursors-chemicals', image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=900&q=85', count: 34 },
  { name: 'Vacuum & Pumping', slug: 'vacuum-pumping', image: 'https://images.unsplash.com/photo-1602052577122-f73b9710adba?auto=format&fit=crop&w=900&q=85', count: 46 },
  { name: 'Quartz & Chamber Parts', slug: 'quartz-chamber-parts', image: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?auto=format&fit=crop&w=900&q=85', count: 61 },
  { name: 'N2 Generators', slug: 'n2-generators', image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=85', count: 18 },
  { name: 'Chillers', slug: 'chillers', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=85', count: 16 },
]

const products: Product[] = [
  { id: 'vcr-316', name: '316L VCR Diaphragm Valve', part: 'ALD-V-316L-14', vendor: 'Swagelok', category: 'Valves & Flow Control', spec: '1/4 in · 2-way · 150°C', price: 428, image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=85', processes: ['ALD', 'ALE'], featured: true },
  { id: 'bubbler-250', name: '250 mL Precursor Bubbler', part: 'PCT-BUB-250-SS', vendor: 'Picosun', category: 'Precursor Containers & Bubblers', spec: '316L · 250 mL · 200°C', price: 1260, image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1000&q=85', processes: ['ALD', 'MLD'], featured: true },
  { id: 'oring-kalrez', name: 'Kalrez® 9100 O-ring Set', part: 'KAL-9100-214-SET', vendor: 'DuPont', category: 'Gaskets & O-rings', spec: 'Size 214 · FFKM · 260°C', price: 186, image: 'https://images.unsplash.com/photo-1565600225326-8e9ef7e6e6c0?auto=format&fit=crop&w=1000&q=85', processes: ['ALD', 'ALE', 'MLD'] },
  { id: 'turbo-700', name: '700 L/s Mag-Lev Turbo Pump', part: 'TMP-700-ALD-M', vendor: 'Edwards', category: 'Vacuum & Pumping', spec: '700 L/s · ISO 160 · 10⁻⁹ mbar', price: 8940, image: 'https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&w=1000&q=85', processes: ['ALD', 'ALE'] },
  { id: 'quartz-liner', name: 'Quartz Chamber Liner', part: 'QZ-LINER-200-4', vendor: 'Heraeus', category: 'Quartz & Chamber Parts', spec: 'Fused quartz · 200 mm · 1.5 mm', price: 2380, image: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?auto=format&fit=crop&w=1000&q=85', processes: ['ALD', 'MLD'] },
  { id: 'tc-k-type', name: 'K-Type Sheathed Thermocouple', part: 'TC-K-6-300-ALD', vendor: 'Omega Engineering', category: 'Thermocouples', spec: '6 mm · 300 mm · ±1.5°C', price: 214, image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=85', processes: ['ALD', 'ALE', 'MLD'] },
]

export { products, categories }

function AppLogo({ dark = false }: { dark?: boolean }) {
  return <Link to="/" className="group flex shrink-0 items-center gap-2.5" aria-label="ALD Pulse home"><span className={`grid size-8 place-items-center rounded-[10px] ${dark ? 'bg-background text-foreground' : 'bg-foreground text-background'} transition-transform duration-300 group-hover:rotate-6`}><svg viewBox="0 0 32 32" fill="none" aria-hidden="true" className="size-[18px]"><path d="M2 22.4C6.1 15.4 10.8 13.2 16.2 14.7c4.7 1.3 7.7-.5 13.8-8.1-4.7 8.4-9.8 13.2-15.5 14.3-5.1 1-8.8-2.2-12.5-1.5Z" fill="currentColor" /><path d="M2.8 19.5c4.2-5.8 8.6-7.3 13.4-6.1 4.4 1.1 7.5-.6 13.8-6.8-5.4 7.8-9.4 10.9-14 11.5-4.9.7-8.1-2-13.2 1.4Z" fill="currentColor" /></svg></span><span className="text-[17px] font-bold tracking-[-0.06em]">ALD Pulse</span></Link>
}

function CategoryMenu({ mobile = false, onNavigate }: { mobile?: boolean; onNavigate?: () => void }) {
  const [open, setOpen] = useState(false)
  return <div className={mobile ? 'flex flex-col gap-1' : 'relative'}>
    <button onClick={() => setOpen(value => !value)} aria-expanded={open} className={`flex items-center gap-1.5 font-semibold transition-colors ${mobile ? 'w-full justify-between border-b border-primary-foreground/15 py-3 text-left' : 'py-3 hover:text-primary-foreground/75'}`}><span>Categories</span><ChevronDown className={`size-3.5 transition-transform ${open ? 'rotate-180' : ''}`} /></button>
    {open && <div className={`${mobile ? 'mt-1 grid gap-1 pl-3' : 'absolute left-1/2 top-full z-50 grid w-[520px] -translate-x-1/2 grid-cols-2 gap-1 rounded-b-xl border border-border bg-background p-3 text-foreground shadow-lg'}`}>
      {categories.map(category => <Link key={category.slug} to="/catalog" search={{ category: category.name }} onClick={() => { setOpen(false); onNavigate?.() }} className="group flex items-center justify-between rounded-lg px-3 py-2.5 text-sm hover:bg-accent hover:text-primary"><span>{category.name}</span><span className="font-mono text-[10px] text-muted-foreground group-hover:text-primary">{category.count}</span></Link>)}
    </div>}
  </div>
}

function SiteHeader() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const nav = <><Link to="/" onClick={() => setMobileOpen(false)} className="font-semibold transition-colors hover:text-primary-foreground/75">Home</Link><CategoryMenu mobile onNavigate={() => setMobileOpen(false)} /><Link to="/coating-services" onClick={() => setMobileOpen(false)} className="border-b border-primary-foreground/15 py-3 font-semibold transition-colors hover:text-primary-foreground/75 lg:border-0 lg:py-0">ALD Coating Services</Link><Link to="/database" onClick={() => setMobileOpen(false)} className="border-b border-primary-foreground/15 py-3 font-semibold transition-colors hover:text-primary-foreground/75 lg:border-0 lg:py-0">Database</Link><Link to="/precursors" onClick={() => setMobileOpen(false)} className="border-b border-primary-foreground/15 py-3 font-semibold transition-colors hover:text-primary-foreground/75 lg:border-0 lg:py-0">ALD Precursors</Link><Link to="/about" onClick={() => setMobileOpen(false)} className="border-b border-primary-foreground/15 py-3 font-semibold transition-colors hover:text-primary-foreground/75 lg:border-0 lg:py-0">About Us</Link><a href="mailto:hello@aldpulse.com" onClick={() => setMobileOpen(false)} className="py-3 font-semibold transition-colors hover:text-primary-foreground/75 lg:py-0">Contact Us</a></>
  return <header className="sticky top-0 z-50 border-b border-foreground/10 bg-foreground text-background shadow-lg"><div className="flex min-h-[68px] w-full items-center justify-between gap-8 px-5 lg:px-10 xl:px-14"><AppLogo dark /><nav className="hidden flex-1 items-center justify-center gap-7 text-[13px] lg:flex"><Link to="/" className="font-semibold transition-colors hover:text-background/70">Home</Link><CategoryMenu /><Link to="/coating-services" className="font-semibold transition-colors hover:text-background/70">ALD Coating Services</Link><Link to="/database" className="font-semibold transition-colors hover:text-background/70">Database</Link><Link to="/precursors" className="font-semibold transition-colors hover:text-background/70">ALD Precursors</Link><Link to="/about" className="font-semibold transition-colors hover:text-background/70">About Us</Link><Link to="/contact" className="font-semibold transition-colors hover:text-background/70">Contact Us</Link></nav><div className="hidden items-center gap-3 text-xs lg:flex"><button className="flex items-center gap-1.5 rounded-md px-2 py-2 hover:bg-background/10"><Globe2 className="size-3.5" /> EN <ChevronDown className="size-3" /></button><button className="rounded-md px-2 py-2 hover:bg-background/10">USD <ChevronDown className="ml-1 inline size-3" /></button><Link to="/account" className="rounded-full border border-background/35 px-4 py-2 font-semibold transition-colors hover:bg-background hover:text-foreground">Sign In</Link></div><Sheet open={mobileOpen} onOpenChange={setMobileOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" className="text-background hover:bg-background/10 hover:text-background lg:hidden"><Menu /></Button></SheetTrigger><SheetContent side="right" className="w-[min(88vw,370px)] bg-foreground text-background"><div className="mt-8 flex flex-col gap-2 text-base">{nav}<Link to="/account" onClick={() => setMobileOpen(false)} className="mt-4 border-t border-background/20 pt-5 font-semibold">Sign In</Link></div></SheetContent></Sheet></div></header>
}

const heroBanners = [
  { label: 'QUALIFIED SUPPLY', title: 'Built around your deposition process.', body: 'Find compatible components, chemistry, and instrumentation from trusted manufacturers.', image: categories[0].image },
  { label: 'ONE MARKETPLACE', title: 'Every part for a cleaner pulse.', body: 'ALD, ALE, and MLD sourcing without the supplier chase.', image: categories[3].image },
  { label: 'PROCESS CONFIDENCE', title: 'Specification-first procurement.', body: 'Compare vendors and technical details before you contact the supply desk.', image: categories[6].image },
]

function Banner() {
  const [active, setActive] = useState(0)
  useEffect(() => { const timer = window.setInterval(() => setActive(value => (value + 1) % heroBanners.length), 5200); return () => window.clearInterval(timer) }, [])
  const banner = heroBanners[active]
  return <section className="relative isolate overflow-hidden bg-foreground text-background"><AnimatePresence mode="wait"><motion.div key={active} initial={{ opacity: 0, scale: 1.03 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }} transition={{ duration: .7 }} className="relative min-h-[330px] sm:min-h-[370px] lg:min-h-[400px]"><img src={banner.image} alt="ALD Pulse featured supply" className="absolute inset-0 h-full w-full object-cover opacity-35 mix-blend-screen" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_82%_35%,transparent_0%,rgb(29_29_31_/_0.3)_48%,rgb(29_29_31_/_0.94)_100%)]" /><div className="absolute inset-0 bg-gradient-to-r from-foreground via-foreground/80 to-transparent" /><div className="relative mx-auto flex min-h-[330px] max-w-[1440px] items-end px-6 pb-14 sm:min-h-[370px] sm:px-10 sm:pb-16 lg:min-h-[400px] lg:px-20 lg:pb-20"><div className="max-w-3xl"><p className="font-mono text-[10px] font-bold tracking-[.22em] text-background/60">{banner.label} · 0{active + 1}</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold leading-[.98] tracking-[-.065em] sm:text-5xl lg:text-6xl">{banner.title}</h2><p className="mt-4 max-w-lg text-sm leading-6 text-background/70 sm:text-base">{banner.body}</p><Link to="/catalog" className="mt-6 inline-flex items-center gap-3 rounded-full bg-background px-5 py-3 text-sm font-bold text-foreground transition hover:-translate-y-0.5 hover:bg-background/90">Explore the marketplace <ChevronDown className="size-4 -rotate-90" /></Link></div></div></motion.div></AnimatePresence><div className="absolute bottom-6 right-6 flex items-center gap-2 sm:right-10 lg:right-20">{heroBanners.map((item, index) => <button key={item.label} onClick={() => setActive(index)} aria-label={`Show banner ${index + 1}`} className={`h-1.5 rounded-full transition-all ${active === index ? 'w-9 bg-background' : 'w-1.5 bg-background/45'}`} />)}</div></section>
}

function CategoryTile({ category }: { category: Category }) {
  return <Link to="/catalog" search={{ category: category.name }} className="group grid min-w-0 grid-rows-[1fr_42px] overflow-hidden rounded-[10px] border border-border bg-background shadow-sm transition-all hover:-translate-y-1 hover:border-primary/50 hover:shadow-md"><div className="relative min-h-0 overflow-hidden bg-secondary"><img src={category.image} alt={category.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-foreground/60 via-transparent to-transparent" /></div><div className="flex min-h-0 items-center justify-between gap-1 px-1.5 py-1"><span className="line-clamp-2 text-[9px] font-bold leading-[1.05] text-foreground">{category.name}</span><span className="shrink-0 font-mono text-[8px] text-muted-foreground">{category.count}</span></div></Link>
}

function RegistrationModal({ onClose }: { onClose: () => void }) { const [email, setEmail] = useState(''); return <div className="fixed inset-0 z-[60] grid place-items-center bg-foreground/40 p-5 backdrop-blur-sm" onMouseDown={onClose}><div className="w-full max-w-md rounded-2xl bg-background p-7 shadow-lg" onMouseDown={event => event.stopPropagation()}><div className="flex items-center justify-between"><p className="font-mono text-[10px] font-bold tracking-[.2em] text-primary">MEMBER PRICE ACCESS</p><button onClick={onClose} aria-label="Close" className="rounded-full p-2 text-muted-foreground hover:bg-secondary"><X className="size-4" /></button></div><h3 className="mt-4 text-2xl font-semibold tracking-tight">Register to see pricing</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Enter your work email. We’ll send a confirmation link before showing member pricing and adding you to the ALD Pulse sourcing network.</p><Input value={email} onChange={event => setEmail(event.target.value)} type="email" placeholder="you@company.com" className="mt-6 h-12 rounded-lg bg-secondary" /><Button onClick={() => { if (!email) return; toast.success('Confirmation instructions sent to your inbox.'); onClose() }} className="mt-4 h-11 w-full rounded-lg font-bold">Send confirmation email</Button></div></div> }

function ProductPreview() { const [modal, setModal] = useState(false); const product = products[0]; return <section className="border-y border-border bg-secondary/45"><div className="mx-auto grid max-w-[1440px] items-center gap-12 px-6 py-20 sm:px-10 lg:grid-cols-[.85fr_1.15fr] lg:px-20 lg:py-28"><div className="group overflow-hidden rounded-2xl bg-background shadow-lg"><img src={product.image} alt={product.name} className="aspect-[1.2] w-full object-cover transition-transform duration-700 group-hover:scale-105" /></div><div><p className="font-mono text-[10px] font-bold tracking-[.2em] text-primary">FEATURED PART · {product.vendor}</p><h2 className="mt-4 max-w-xl text-4xl font-semibold leading-[1.02] tracking-[-.06em] text-foreground sm:text-5xl">The right component changes the whole process.</h2><p className="mt-5 max-w-xl text-base leading-7 text-muted-foreground">{product.name} · {product.spec}. Built for reliable pulse, purge, and isolation cycles in demanding ALD and ALE environments.</p><button onClick={() => setModal(true)} className="mt-8 inline-flex h-12 items-center gap-2 rounded-full bg-primary px-6 text-sm font-bold text-primary-foreground transition hover:-translate-y-0.5 hover:shadow-lg">See price <Search className="size-4" /></button></div></div>{modal && <RegistrationModal onClose={() => setModal(false)} />}</section> }

function HomePage() { return <div className="min-h-dvh overflow-x-hidden bg-background"><SiteHeader /><main><Banner /><section className="mx-auto max-w-[1440px] px-6 pb-8 pt-12 text-center sm:px-10 lg:px-20 lg:pb-10 lg:pt-14"><p className="font-mono text-[10px] font-bold tracking-[.2em] text-primary">ALD PULSE MARKETPLACE · THE TECHNICAL MANUAL</p><h1 className="mx-auto mt-3 max-w-5xl text-4xl font-semibold leading-[.98] tracking-[-.065em] text-foreground sm:text-5xl">Source with confidence.<br className="hidden sm:block" /> Build with precision.</h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">Browse process-ready components and chemistry by category, manufacturer, and technical specification.</p></section><section className="mx-auto max-w-[1140px] px-6 pb-10 sm:px-8 lg:px-10"><div className="flex items-end justify-between border-b border-border pb-3"><div><p className="font-mono text-[10px] font-bold tracking-[.2em] text-primary">SHOP BY CATEGORY</p><h2 className="mt-1.5 text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">Find the part in your process</h2></div><Link to="/catalog" className="hidden items-center gap-2 text-sm font-bold text-primary sm:flex">View all <ChevronDown className="size-4 -rotate-90" /></Link></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6 xl:grid-cols-11">{categories.map(category => <CategoryTile category={category} key={category.slug} />)}</div></section></main><footer className="flex flex-col gap-5 bg-foreground px-6 py-10 text-background sm:flex-row sm:items-center sm:justify-between lg:px-20"><div><AppLogo dark /><p className="mt-3 max-w-sm text-sm text-background/60">A specification-first marketplace for ALD, ALE, and MLD sourcing.</p></div><div className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-background/65"><Link to="/catalog" className="hover:text-background">Categories</Link><Link to="/about" className="hover:text-background">About Us</Link><Link to="/contact" className="hover:text-background">Contact Us</Link><Link to="/account" className="hover:text-background">Sign In</Link></div></footer></div> }
