/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as PrecursorsRouteImport } from './routes/precursors'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CoatingServicesRouteImport } from './routes/coating-services'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as VendorVendorRouteImport } from './routes/vendor.$vendor'
import { Route as ProductProductRouteImport } from './routes/product.$product'

const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecursorsRoute = PrecursorsRouteImport.update({
  id: '/precursors',
  path: '/precursors',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CoatingServicesRoute = CoatingServicesRouteImport.update({
  id: '/coating-services',
  path: '/coating-services',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const VendorVendorRoute = VendorVendorRouteImport.update({
  id: '/vendor/$vendor',
  path: '/vendor/$vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductRoute = ProductProductRouteImport.update({
  id: '/product/$product',
  path: '/product/$product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/coating-services': typeof CoatingServicesRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/database': typeof DatabaseRoute
  '/precursors': typeof PrecursorsRoute
  '/rfq': typeof RfqRoute
  '/product/$product': typeof ProductProductRoute
  '/vendor/$vendor': typeof VendorVendorRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/coating-services': typeof CoatingServicesRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/database': typeof DatabaseRoute
  '/precursors': typeof PrecursorsRoute
  '/rfq': typeof RfqRoute
  '/product/$product': typeof ProductProductRoute
  '/vendor/$vendor': typeof VendorVendorRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/coating-services': typeof CoatingServicesRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/database': typeof DatabaseRoute
  '/precursors': typeof PrecursorsRoute
  '/rfq': typeof RfqRoute
  '/product/$product': typeof ProductProductRoute
  '/vendor/$vendor': typeof VendorVendorRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/app'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/coating-services'
    | '/compare'
    | '/contact'
    | '/database'
    | '/precursors'
    | '/rfq'
    | '/product/$product'
    | '/vendor/$vendor'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/coating-services'
    | '/compare'
    | '/contact'
    | '/database'
    | '/precursors'
    | '/rfq'
    | '/product/$product'
    | '/vendor/$vendor'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/app'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/coating-services'
    | '/compare'
    | '/contact'
    | '/database'
    | '/precursors'
    | '/rfq'
    | '/product/$product'
    | '/vendor/$vendor'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AppRoute: typeof AppRouteWithChildren
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  CoatingServicesRoute: typeof CoatingServicesRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DatabaseRoute: typeof DatabaseRoute
  PrecursorsRoute: typeof PrecursorsRoute
  RfqRoute: typeof RfqRoute
  ProductProductRoute: typeof ProductProductRoute
  VendorVendorRoute: typeof VendorVendorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precursors': {
      id: '/precursors'
      path: '/precursors'
      fullPath: '/precursors'
      preLoaderRoute: typeof PrecursorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coating-services': {
      id: '/coating-services'
      path: '/coating-services'
      fullPath: '/coating-services'
      preLoaderRoute: typeof CoatingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/vendor/$vendor': {
      id: '/vendor/$vendor'
      path: '/vendor/$vendor'
      fullPath: '/vendor/$vendor'
      preLoaderRoute: typeof VendorVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$product': {
      id: '/product/$product'
      path: '/product/$product'
      fullPath: '/product/$product'
      preLoaderRoute: typeof ProductProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AppRoute: AppRouteWithChildren,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  CoatingServicesRoute: CoatingServicesRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DatabaseRoute: DatabaseRoute,
  PrecursorsRoute: PrecursorsRoute,
  RfqRoute: RfqRoute,
  ProductProductRoute: ProductProductRoute,
  VendorVendorRoute: VendorVendorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
